### ISSUE TITLE
Add WindiCSS as an UI Framework

### ISSUE THREAD

**Issue by shadyar-bakr** [nuxtlabs/vue-telescope-analyzer#55]
Add windicss as UI framework to separate sites who use tailwind and windi.

GitHub Repo: https://github.com/windicss/windicss
Website: https://windicss.org/

**Comment by antfu** [comment]
The problem is that windicss generates css that does not have much identification. I checked the detector for tailwind and it matches with the varients like `sm:` `md:`, from that perspective there is not too much difference between tailwind and windicss. We could do the detection with windicss-only features (new varients, attributify, etc.) but that would really depend on if users have used those features and potentially make the result inaccurate (or is that acceptable?)

**Comment by shadear** [comment]
Yeah, it is very difficult and tricky to till them apart. 
Speaking of similarity, windicss still use `--tw` as prefix like in `--tw-ring-inset: var(--tw-empty,/*!*/ /*!*/);` or `--tw-border-opacity: 1;`, if we change that will it be enough to till them apart?
